[package]
name = "watershed"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
imageproc = "0.26.0"
rand = "0.9.2"

[patch.crates-io]
imageproc = { path = "/Users/orange/rust-projects/orange-imageproc" }
